version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver2019
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: DockerCibertec01_
    networks:
      - fullstack
#  frontend: 
#    container_name: frontend
#    build: ./frontend/website 
#    ports: 
#    - '4200:4200'
#    command: > 
#      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --disable-host-check"
#    networks:
#      - fullstack
#    depends_on:
#      - backend      
  backend:
    container_name: backend
    build: ./BackEnd/springproject
    ports:
      - "8080:8080"
    networks:
      - fullstack
    depends_on:
      - sqlserver
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=DockerCibertec01_
      - DATABASE_NAME=BDPets  
      - DATABASE_PORT=1433
networks:
  fullstack:
