version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver2019
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: CibertecDemo01_
    networks:
    - cibertec
  backend:
    container_name: backend
    build: ./demo
    ports:
      - 8085:8085
networks:
  cibertec: